Set up action
standout/hekto-github-action pull request #1
Opened 2020-06-17 09:10 UTC by simontollstern

Kanske lite mycket `echo`s i entrypointen, idk

2020-06-18 14:42 UTC, frdrkolsson requested changes
🚀

2020-06-18 14:42 UTC, frdrkolsson commented on README.md
> +  token: 'ukBGtVBVk1uCEgZhayJkjxMsaBwM9H72dXe5ULW1AgFyTvBo'
Är detta ett riktigt token? Vi kanske inte vill ha såna grejer i klartext i en readme!

2020-06-18 14:42 UTC, frdrkolsson commented on entrypoint.sh
> +response=$(curl -X POST -d file_name=$file_name -d file_size=$file_size -d commit=$git_hash http://hekto.local:3000/sv/api/v1/deployment -H "Authorization: Bearer $1")
Vi borde nog läsa adressen annorlunda än att ta local, som att beroende på vilken `RAILS_ENV` vi har, sätta en variabel som heter `hekto_url` eller något

2020-06-18 14:42 UTC, frdrkolsson commented on entrypoint.sh
> +curl=$(curl -X PUT http://hekto.local:3000/sv/api/v1/deployment/$deployment -H "Authorization: Bearer $1")
Vi borde nog läsa adressen annorlunda än att ta local, som att beroende på vilken `RAILS_ENV` vi har, sätta en variabel som heter `hekto_url` eller något

2020-06-22 10:34 UTC, simontollstern commented on README.md
> +  token: 'ukBGtVBVk1uCEgZhayJkjxMsaBwM9H72dXe5ULW1AgFyTvBo'
Genererade en ny token och la där som exempel bara

2020-06-22 14:17 UTC, simontollstern commented on entrypoint.sh
> +response=$(curl -X POST -d file_name=$file_name -d file_size=$file_size -d commit=$git_hash http://hekto.local:3000/sv/api/v1/deployment -H "Authorization: Bearer $1")
Ändrade till `hekto.app` istället bara
Kanske bör finnas en funktion för att skicka till stagingsidan med, men tror inte det är superviktigt just nu

2020-06-23 08:39 UTC, frdrkolsson approved these changes
Tror denna är fin!

2020-06-23 08:48 UTC, frdrkolsson commented on entrypoint.sh
> +response=$(curl -X POST -d file_name=$file_name -d file_size=$file_size -d commit=$git_hash http://hekto.local:3000/sv/api/v1/deployment -H "Authorization: Bearer $1")
Det kan du ju lätt titta på om du läser av vad `RAILS_ENV` är och kommer vara väldigt skönt att testa detta i staging också!

2020-06-24 07:28 UTC, merged